services:
  postgres:
    image: postgres:15
    container_name: fantasypicks-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fantasypicks
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
